# This is a basic workflow to help you get started with Actions

name: Build GUI exe with PyInstaller
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: src

      - uses: actions/upload-artifact@v2
        with:
          name: tofu_video_labeller_exe
          path: src/dist/windows
